FROM ubuntu:17.04

VOLUME ["/mnt/ruby"]

COPY script.sh /scripts/script.sh
COPY setup.sh /scripts/setup.sh

RUN chmod +x /scripts/script.sh
RUN chmod +x /scripts/setup.sh
RUN /scripts/setup.sh

WORKDIR /mnt/ruby
CMD ["/usr/local/bin/sft-server","5000","/scripts/scripts.sh"]

EXPOSE tcp:5000
